<?php

namespace App\Http\Middleware;

use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken as Middleware;

class VerifyCsrfToken extends Middleware
{
    /**
     * The URIs that should be excluded from CSRF verification.
     *
     * @var array
     */
    protected $except = [
        '/appLogin',
        '/appRegister',
        '/getInfo',
        '/appChangePasword',
        '/register-mail-otp-verify',
        '/register-mail-otp',
        '/reset-password',
        '/appLogout',
        '/editUserInfo',
        '/appChangeLang',
        '/appUploadDoc',
        '/appOrderHistory',
        '/appProductListing',
        '/accountSetting',
        '/appUploadAvatar',
        '/appProductDetail',
        '/addReview',
        '/productReviewList',
        '/appProductFav',
        '/userWishList',
        '/addToCart',
        '/userCartList',
        '/removeFromCart',
        '/productSearch',
        '/productCategories',
        '/similarProducts',
        '/productFilter',
        '/productFilterTags',
        '/editCart',
        '/faq',
        '/addBillingAddress',
        '/listBillingAddress',
        '/deleteBillingAddress',
        '/editBillingAddress',
        '/appOrderCreate',
        '/addDefaultBillingAddress',
        '/getProductCharges',
        '/checkProductDiscount',
        '/contact_us',
        '/returnProduct',
        '/addInstructionCart',
        '/addUserCardDetails',
        '/editUserCardDetails',
        '/deleteUserCardDetails',
        '/listUserCardDetails',
        '/addDefaultUserCardDetails',
        '/subCategories',
        '/productSubCategories',
        '/categorySearch',
        '/create_customer',
        '/offers',
        '/return_policy',
        '/terms_and_conditions',
        '/offerProducts',
        '/downloadInvoice',
        '/orderPlacedConfirmation',
        '/returnOrderList',
        '/orderHistoryDetails',
        '/stripePost',
        '/stripeToken',
        '/saveData',

        /* Vendor Apps*/
        '/appAddProduct',
        '/appUpdateProduct',
        '/appProductsList',
        '/appDeleteProduct',
        '/getEarningBalance',
        '/getStats',
        '/accountBalance',
        '/service-listing',
        '/categories',
        '/create-service',
        '/update-service',
        '/deleteService',
        '/service-booking',
        '/service-booking-payment',
        '/attachAccount',
        '/getShopInfo',
        '/getOrders',
        '/orderStatusUpdate',
        '/appCreateUpdateShop',
        '/appCategories',
        '/getAccountDetails',
        '/transferBalanceToBankAccount',
        '/withDrawalRequest',
        '/appImageUpload',
        '/appUpdateBookedServiceStatus',
    ];
}
